services:
    zookeeper:
        image: wurstmeister/zookeeper
    kafka1:
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 103.93.59.207
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
