version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
    kafka1:
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.10.10.10
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    kowl:
        image: quay.io/cloudhut/kowl:v1.2.2
        volumes:
            - ./config.yaml:/etc/kowl/config.yaml
        ports:
            - "8080:8080"
        entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
        depends_on:
            - kafka
